In [5]:
import torch

# Load the model
model = torch.load('./crawl_policy.pt')
#projected_gravity 3
# velocity_commands 3
# joint_pos 23
# joint_vel 23
#  actions 23)
# random_input = torch.randn(75)  # Example shape for image input


# output = model(random_input)


In [7]:
model

{'model_state_dict': OrderedDict([('std',
               tensor([0.5952, 0.5942, 0.6582, 0.2506, 0.2634, 0.4781, 0.4823, 0.3006, 0.3050,
                       0.9858, 0.9498, 0.7936, 0.7990, 0.7981, 0.8222, 0.9156, 0.9244, 0.9617,
                       0.9303, 0.7987, 0.7253, 1.3287, 1.3004], device='cuda:0')),
              ('actor.0.weight',
               tensor([[-1.5521,  1.3839, -0.3083,  ..., -0.0246, -0.0423, -0.0270],
                       [-1.0765, -1.2229, -0.0820,  ..., -0.0564,  0.0679, -0.0380],
                       [-0.5424, -0.0643, -1.4306,  ...,  0.3142, -0.0264, -0.0074],
                       ...,
                       [-0.8186,  1.3293, -2.0793,  ...,  0.1899, -0.1226,  0.0840],
                       [ 0.1283,  0.9445,  2.3998,  ..., -0.2479, -0.0381, -0.0230],
                       [-0.3679,  1.6099,  0.5158,  ...,  0.0081,  0.0205, -0.0169]],
                      device='cuda:0')),
              ('actor.0.bias',
               tensor([-1.1569, -0.5667, 